### ISSUE TITLE
[1.20.1] Patchouli integration broke

### ISSUE THREAD

**Issue by gardenappl** [baileyholl/Ars-Creo#12]
I get this error on startup:
```
[10Sep2023 01:06:06.174] [Worker-ResourceReload-0/ERROR] [patchouli/]: Failed to load book ars_creo:artificers_notes defined by mod ars_creo, skipping
java.lang.IllegalArgumentException: Book ars_creo:artificers_notes has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable 
this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120
 for details.
        at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FORGE.jar%23689!/:1.20.1-81-FORGE]
        at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FORGE.jar%23689!/:1.20.1-81-FORGE]
        at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FORGE.jar%23689!/:1.20.1-81-FORGE]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FORGE.jar%23689!/:1.20.1-81-FORGE]
        at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:76) ~[Patchouli-1.20.1-81-FORGE.jar%23689!/:1.20.1-81-FORGE]
        at vazkii.patchouli.forge.common.__ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[Patchouli-1.20.1-81-FORGE.jar%23689!/:1.20.1-81-FORGE]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23127!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.20.1-47.1.3.jar%23796!/:?]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[fmlcore-1.20.1-47.1.3.jar%23795!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by Bob74** [comment]
Pushed a PR to fix this issue (https://github.com/baileyholl/Ars-Creo/pull/13)

I'm leaving the fixed jar here if someone needs it: 
[ars_creo-1.20.1-4.0.1.jar.zip](https://github.com/baileyholl/Ars-Creo/files/12707420/ars_creo-1.20.1-4.0.1.jar.zip)

**Comment by guivnf** [comment]
> Pushed a PR to fix this issue (#13)
> 
> I'm leaving the fixed jar here if someone needs it: [ars_creo-1.20.1-4.0.1.jar.zip](https://github.com/baileyholl/Ars-Creo/files/12707420/ars_creo-1.20.1-4.0.1.jar.zip)

Could you publish these changes to your CF page please 😅
